"""Generate src/gd_names.h: decorated export names for the symbols we hook/call,
resolved by regex over the undecorated listings in tools/exports (run gen_exports.py first).
Each entry must match exactly one export; the build fails loudly otherwise."""
import re, os, sys
HERE = os.path.dirname(__file__)
ENTRIES = [
    # (identifier, dll, regex over undecorated signature)
    ("LocalizationManager_GetText", "Engine", r"GAME::LocalizationManager::GetText\(char const \*"),
    ("LocalizationManager_LocalizeWithoutParams", "Engine", r"GAME::LocalizationManager::LocalizeWithoutParams\(char const \*"),
    ("Display_Update", "Engine", r"GAME::Display::Update\(void\)"),
    ("WinWindow_OnToggleFullscreen", "Engine", r"GAME::WinWindow::OnToggleFullscreen\(void\)"),   # Alt+Enter; refused (src/hooks.cpp)
    ("Engine_Update", "Engine", r"GAME::Engine::Update\(class GAME::Sphere const"),
    # ---- in-game objects (src/world.cpp) ----
    ("GameEngine_Update", "Game", r"GAME::GameEngine::Update\(int\)"),
    ("GameEngine_GetMainPlayer", "Game", r"GAME::GameEngine::GetMainPlayer\(void\)"),
    ("GameEngine_GetCamera", "Game", r"GAME::GameEngine::GetCamera\(void\)"),
    ("GameEngine_GetAllTargetsInRadius", "Game", r"GAME::GameEngine::GetAllTargetsInRadius\("),
    ("ControllerPlayer_Update", "Game", r"GAME::ControllerPlayer::Update\(int\)"),
    ("ControllerPlayer_SetCombatEnemy", "Game", r"GAME::ControllerPlayer::SetCombatEnemy\("),
    ("ControllerPlayer_SetCommandRepeated", "Game", r"GAME::ControllerPlayer::SetCommandRepeated\(bool\)"),
    ("ControllerPlayer_GetCombatEnemy", "Game", r"GAME::ControllerPlayer::GetCombatEnemy\("),
    ("ControllerPlayer_ClearTarget", "Game", r"GAME::ControllerPlayer::ClearTarget\("),
    ("ControllerPlayer_FaceTarget", "Game", r"GAME::ControllerPlayer::FaceTarget\("),
    ("ControllerPlayer_HandleActionFromJoystick", "Game", r"GAME::ControllerPlayer::HandleActionFromJoystick\("),
    ("ControllerPlayer_HandleActionFromMouse", "Game", r"GAME::ControllerPlayer::HandleActionFromMouse\("),
    ("HotSlotOptionSkill_Activate", "Game", r"GAME::HotSlotOptionSkill::Activate\("),
    ("ControllerPlayer_SetMouseRepeatData", "Game", r"GAME::ControllerPlayer::SetMouseRepeatData\("),
    ("ControllerPlayer_SetCombatAlly", "Game", r"GAME::ControllerPlayer::SetCombatAlly\("),
    ("ControllerAI_MoveTo", "Game", r"GAME::ControllerAI::MoveTo\(class GAME::WorldVec3"),
    ("Character_GetRunSpeed", "Game", r"GAME::Character::GetRunSpeed\("),
    ("ControllerPlayer_SetControllerDirection", "Game", r"GAME::ControllerPlayer::SetControllerDirection\("),
    ("ControllerPlayer_GetControllerDirection", "Game", r"GAME::ControllerPlayer::GetControllerDirection\("),
    ("ControllerPlayer_SetControllerMovementLength", "Game", r"GAME::ControllerPlayer::SetControllerMovementLength\("),
    ("Entity_GetCoords", "Engine", r"GAME::Entity::GetCoords\(void\)"),
    ("Entity_GetRegion", "Engine", r"GAME::Entity::GetRegion\(void\)"),
    ("Resource_GetFileName", "Engine", r"GAME::Resource::GetFileName\(void\)"),   # names a map icon's custom symbol texture (docs/map-icons.md)
    ("Character_GetFootCoords", "Game", r"GAME::Character::GetFootCoords\(bool\)"),
    ("Character_GetCurrentLife", "Game", r"GAME::Character::GetCurrentLife\(void\)"),
    ("Character_GetLifeLimit", "Game", r"GAME::Character::GetLifeLimit\(void\)"),
    ("Character_GetCurrentMana", "Game", r"GAME::Character::GetCurrentMana\(void\)"),   # "Energy" in the UI
    ("Character_GetManaLimit", "Game", r"GAME::Character::GetManaLimit\(void\)"),
    # combat text: the floating numbers / Miss / Dodge / Block are GameEvents of type 0x1b (src/combat.cpp)
    ("EventManager_Send", "Engine", r"GAME::EventManager::Send\(struct GAME::GameEvent const"),
    # combat perception (src/combat.cpp, src/world.cpp, src/notify.cpp): status effects, nameplate, banners
    # ---- enemy skill activations (src/casts.cpp): the animation-driven cast pipeline. NOT listed on purpose:
    # SkillActivated::StartAction/HitAction/ActivateNow (folded shared stubs: hooking them detours ~2000 exports),
    # Suicide::StartAction (== BuffSelf's), BuffOther/Weapon/Suicide::HitAction (== BuffSelf's thunk). ----
    ("SkillActivatedBuffOther_StartAction", "Game", r"GAME::SkillActivatedBuffOther::StartAction\("),
    ("SkillActivatedBuffSelf_StartAction", "Game", r"GAME::SkillActivatedBuffSelf::StartAction\("),
    ("SkillActivatedSpell_StartAction", "Game", r"GAME::SkillActivatedSpell::StartAction\("),
    ("SkillActivatedWeapon_StartAction", "Game", r"GAME::SkillActivatedWeapon::StartAction\("),
    ("SkillActivatedWeaponPool_StartAction", "Game", r"GAME::SkillActivatedWeaponPool::StartAction\("),
    ("SkillActivatedBuffSelf_HitAction", "Game", r"GAME::SkillActivatedBuffSelf::HitAction\("),
    ("SkillActivatedSpell_HitAction", "Game", r"GAME::SkillActivatedSpell::HitAction\("),
    ("SkillActivatedWeaponPool_HitAction", "Game", r"GAME::SkillActivatedWeaponPool::HitAction\("),
    ("SkillActivated_EndAction", "Game", r"GAME::SkillActivated::EndAction\("),
    ("SkillActivatedWeapon_EndAction", "Game", r"GAME::SkillActivatedWeapon::EndAction\("),
    ("SkillActivatedWeaponPool_EndAction", "Game", r"GAME::SkillActivatedWeaponPool::EndAction\("),
    ("Skill_AttackRadius_ActivateNow", "Game", r"GAME::Skill_AttackRadius::ActivateNow\("),
    ("Skill_AttackWave_ActivateNow", "Game", r"GAME::Skill_AttackWave::ActivateNow\("),
    ("Skill_AttackProjectileAreaEffect_ActivateNow", "Game", r"GAME::Skill_AttackProjectileAreaEffect::ActivateNow\("),
    ("Skill_AttackWeapon_ActivateNow", "Game", r"GAME::Skill_AttackWeapon::ActivateNow\("),
    ("Skill_AttackProjectile_ActivateNow", "Game", r"GAME::Skill_AttackProjectile::ActivateNow\("),
    ("Skill_AttackProjectileBurst_ActivateNow", "Game", r"GAME::Skill_AttackProjectileBurst::ActivateNow\("),
    ("SkillManager_HandleSkillAnimationCallback", "Game", r"GAME::SkillManager::HandleSkillAnimationCallback\("),
    ("Character_AnimationCallback", "Game", r"GAME::Character::AnimationCallback\("),
    ("Character_GetRemainingAnimationTime", "Game", r"GAME::Character::GetRemainingAnimationTime\(void\)"),
    ("CombatManager_TakeAttack", "Game", r"GAME::CombatManager::TakeAttack\("),   # the victim-side hit resolver (this = the victim's CombatManager, Character* at +8)
    ("Character_DebufTarget", "Game", r"GAME::Character::DebufTarget\(class GAME::Character & __ptr64,bool,struct GAME::SkillBuffTransfer const"),
    ("Monster_GetClassification", "Game", r"GAME::Monster::GetClassification\(void\)"),
    ("Monster_GetExperienceReward", "Game", r"GAME::Monster::GetExperienceReward\("),
    ("GameEngine_AddUINotification_Str", "Game", r"GAME::GameEngine::AddUINotification\(enum GAME::UINotification::Type,class std::basic_string"),
    ("GameEngine_AddUINotification_Vec", "Game", r"GAME::GameEngine::AddUINotification\(enum GAME::UINotification::Type,class mem::vector"),
    ("ControllerPlayer_SetUserText", "Game", r"GAME::ControllerPlayer::SetUserText\("),
    # Kill feedback: PlayStats::IncrementKills fires once per player-credited kill (confirmed live 2026-08-25 --
    # HandleExperienceNotification / SkillManager::OnEnemyDeath do NOT fire/credit in single-player). Args
    # (a1, a2, MonsterClassification, bool); XP is read by polling GetExperiencePoints (no XP-event hook fires).
    ("PlayStats_IncrementKills", "Game", r"GAME::PlayStats::IncrementKills\("),
    ("Player_GetPlayerName", "Game", r"GAME::Player::GetPlayerName\(void\)"),
    ("Region_GetName", "Engine", r"GAME::Region::GetName\(void\)"),
    # world structure (chunks = the engine's Regions, their portals; docs/rooms.md)
    ("World_GetNumRegions", "Engine", r"GAME::World::GetNumRegions\(void\)"),
    ("World_GetRegion", "Engine", r"GAME::World::GetRegion\(int\)"),
    ("Region_GetOffsetFromWorld", "Engine", r"GAME::Region::GetOffsetFromWorld\(void\)"),
    ("Region_IsUnderground", "Engine", r"GAME::Region::IsUnderground\(void\)"),
    ("Region_IsLevelLoaded", "Engine", r"GAME::Region::IsLevelLoaded\(void\)"),
    ("Region_BackgroundLoadLevel", "Engine", r"GAME::Region::BackgroundLoadLevel\(bool\)"),
    ("Region_IsLoadingFinished", "Engine", r"GAME::Region::IsLoadingFinished\(void\)"),   # level attached and the loading byte clear (/settle)
    ("Engine_GetResourceLoader", "Engine", r"GAME::Engine::GetResourceLoader\(void\)"),
    ("ResourceLoader_IsIdle", "Engine", r"GAME::ResourceLoader::IsIdle\(void\)"),   # zero-timeout wait on the loader's work event
    ("IsGameTimePaused", "Engine", r"GAME::IsGameTimePaused\(void\)"),
    ("PauseGameTime", "Engine", r"GAME::PauseGameTime\(void\)"),
    ("UnpauseGameTime", "Engine", r"GAME::UnpauseGameTime\(void\)"),
    ("Region_GetNumPortals", "Engine", r"GAME::Region::GetNumPortals\(void\)"),
    ("Region_GetPortal", "Engine", r"GAME::Region::GetPortal\(int\)"),
    ("Region_GetWorldIndex", "Engine", r"GAME::Region::GetWorldIndex\(void\)"),
    ("Region_GetBoundingBox", "Engine", r"GAME::Region::GetBoundingBox\(void\)"),
    ("Portal_GetConnectedRegion", "Engine", r"GAME::Portal::GetConnectedRegion\(void\)"),
    ("Portal_GetChokePoint", "Engine", r"GAME::Portal::GetChokePoint\(void\)"),
    ("Portal_GetIsOpen", "Engine", r"GAME::Portal::GetIsOpen\(void\)"),
    # authoring dev routes (/teleport, /fog): docs/rooms.md
    ("World_GetRegionContainingXZ", "Engine", r"GAME::World::GetRegionContainingXZ\("),
    ("Entity_SetCoords", "Engine", r"GAME::Entity::SetCoords\(class GAME::WorldCoords const"),
    ("Character_TeleportToLocation", "Game", r"GAME::Character::TeleportToLocation\(class GAME::WorldCoords const"),
    ("Region_GetFogOfWar", "Engine", r"GAME::Region::GetFogOfWar\(bool\)"),
    ("FogOfWar_AddVisibility", "Engine", r"GAME::FogOfWar::AddVisibility\("),
    ("FogOfWar_IsInFog", "Engine", r"GAME::FogOfWar::IsInFog\("),
    ("NavManager_Get", "Engine", r"GAME::Singleton<class GAME::NavManager>::Get\(void\)"),
    ("NavManager_IsPointOnPathMesh", "Engine", r"GAME::NavManager::IsPointOnPathMesh\("),
    ("NavManager_FindStraightMovePoint", "Engine", r"GAME::NavManager::FindStraightMovePoint\(class GAME::WorldVec3 const & __ptr64,class GAME::WorldVec3 const & __ptr64,class GAME::WorldVec3 & __ptr64\)"),
    ("NavManager_FindClosestPointOnPathMesh", "Engine", r"GAME::NavManager::FindClosestPointOnPathMesh\("),
    ("NavManager_FindPath", "Engine", r"GAME::NavManager::FindPath\(class GAME::WorldVec3 const & __ptr64,class GAME::WorldVec3 const & __ptr64,float,"),
    ("Player_FindPath", "Game", r"GAME::Player::FindPath\(class GAME::WorldVec3 const & __ptr64,float,class GAME::WorldVec3 & __ptr64,float\)"),
    ("WorldVec3_ctor", "Engine", r"GAME::WorldVec3::WorldVec3\(class GAME::Region \* __ptr64,class GAME::Vec3 const & __ptr64\)"),
    ("WorldVec3_GetWorldPosition", "Engine", r"GAME::WorldVec3::GetWorldPosition\(void\)"),
    ("WorldVec3_GetRegion", "Engine", r"GAME::WorldVec3::GetRegion\(void\)"),
    ("WorldVec3_GetRegionPosition", "Engine", r"GAME::WorldVec3::GetRegionPosition\(void\)"),
    ("WorldVec3_PutOnFloor", "Engine", r"GAME::WorldVec3::PutOnFloor\(void\)"),
    ("WorldCoords_GetRegionCoords", "Engine", r"GAME::WorldCoords::GetRegionCoords\(void\)"),
    ("WorldCamera_GetCameraYaw", "Engine", r"GAME::WorldCamera::GetCameraYaw\(void\)"),
    ("Engine_GetAreaNameTag", "Engine", r"GAME::Engine::GetAreaNameTag\(void\)"),
    # ---- targeting / entities ----
    ("World_Update", "Engine", r"GAME::World::Update\(class mem::vector<class GAME::Sphere>"),
    ("World_GetEntitiesInSphere", "Engine", r"GAME::World::GetEntitiesInSphere\("),
    ("Engine_GetEntitiesInPriorFrameFrustum", "Engine", r"GAME::Engine::GetEntitiesInPriorFrameFrustum\("),
    ("Region_GetEntitiesInSphere", "Engine", r"GAME::Region::GetEntitiesInSphere\("),
    ("Object_GetObjectId", "Engine", r"GAME::Object::GetObjectId\(void\)"),
    ("Entity_GetRegionBoundingBox", "Engine", r"GAME::Entity::GetRegionBoundingBox\(bool\)"),
    ("Object_GetObjectName", "Engine", r"GAME::Object::GetObjectName\(void\)"),
    ("Object_GetRTTIClassInfo", "Engine", r"GAME::Object::GetRTTIClassInfo\(void\)"),
    ("Entity_GetStaticClassInfo", "Engine", r"GAME::Entity::GetStaticClassInfo\(void\)"),
    ("Character_GetStaticClassInfo", "Game", r"GAME::Character::GetStaticClassInfo\(void\)"),
    ("Monster_GetStaticClassInfo", "Game", r"GAME::Monster::GetStaticClassInfo\(void\)"),
    ("ItemEquipment_GetStaticClassInfo", "Game", r"GAME::ItemEquipment::GetStaticClassInfo\(void\)"),
    ("Weapon_GetStaticClassInfo", "Game", r"GAME::Weapon::GetStaticClassInfo\(void\)"),
    ("Weapon_IsTwoHanded", "Game", r"GAME::Weapon::IsTwoHanded\(void\)const"),   # weapon type (vt+0x6b0) 8..9: the two-handed ranged
    ("Weapon_IsTwoHandedMeleeWeapon", "Game", r"GAME::Weapon::IsTwoHandedMeleeWeapon\(void\)const"),   # weapon type 15..18
    ("ItemEquipment_HasRelic", "Game", r"GAME::ItemEquipment::HasRelic\(void\)"),   # a component is attached (docs/re_item_components_compare.md)
    ("Npc_GetStaticClassInfo", "Game", r"GAME::Npc::GetStaticClassInfo\(void\)"),
    ("ItemNote_GetStaticClassInfo", "Game", r"GAME::ItemNote::GetStaticClassInfo\(void\)"),
    ("OneShot_GetStaticClassInfo", "Game", r"GAME::OneShot::GetStaticClassInfo\(void\)"),
    ("ItemArtifactFormula_GetStaticClassInfo", "Game", r"GAME::ItemArtifactFormula::GetStaticClassInfo\(void\)"),
    ("ItemFactionBooster_GetStaticClassInfo", "Game", r"GAME::ItemFactionBooster::GetStaticClassInfo\(void\)"),
    ("ItemFactionWarrant_GetStaticClassInfo", "Game", r"GAME::ItemFactionWarrant::GetStaticClassInfo\(void\)"),
    ("ItemDifficultyUnlock_GetStaticClassInfo", "Game", r"GAME::ItemDifficultyUnlock::GetStaticClassInfo\(void\)"),
    ("ItemDevotionReset_GetStaticClassInfo", "Game", r"GAME::ItemDevotionReset::GetStaticClassInfo\(void\)"),
    ("ItemEnchantment_GetStaticClassInfo", "Game", r"GAME::ItemEnchantment::GetStaticClassInfo\(void\)"),
    ("Player_GetDiscoveredShrineUIDs", "Game", r"GAME::Player::GetDiscoveredShrineUIDs\(void\)"),
    ("Player_GetShrineUIDs", "Game", r"GAME::Player::GetShrineUIDs\(void\)"),
    ("Character_GetVisibleFaction", "Game", r"GAME::Character::GetVisibleFaction\(void\)"),
    ("GameEngine_GetFactionLevelValue", "Game", r"GAME::GameEngine::GetFactionLevelValue\("),
    ("Character_SubtractMoney", "Game", r"GAME::Character::SubtractMoney\(unsigned int\)"),
    ("Player_AddSack", "Game", r"GAME::Player::AddSack\(void\)"),
    ("GameEngine_AddTransferSack", "Game", r"GAME::GameEngine::AddTransferSack\(void\)"),
    ("Player_GetStaticClassInfo", "Game", r"GAME::Player::GetStaticClassInfo\(void\)"),
    ("Character_GetCurrentAttackTarget", "Game", r"GAME::Character::GetCurrentAttackTarget\("),
    ("Character_IsAlive", "Game", r"GAME::Character::IsAlive\(void\)"),
    ("GameEngine_GetFactionManager", "Game", r"GAME::GameEngine::GetFactionManager\(void\)"),
    ("FactionManager_IsFoe", "Game", r"GAME::FactionManager::IsFoe\(unsigned int,unsigned int,bool\)"),
    # ---- conversations (structured source for the dialog screen) ----
    ("Conversation_GetText", "Game", r"GAME::Conversation::GetText\(class GAME::ConversationStep const"),
    ("Conversation_GetSteps", "Game", r"GAME::Conversation::GetSteps\(class GAME::ConversationStep \* __ptr64,class mem::vector"),
    ("Conversation_GetRoot", "Game", r"GAME::Conversation::GetRoot\(void\)"),
    ("ConversationStep_GetType", "Game", r"GAME::ConversationStep::GetType\(void\)"),
    ("ConversationStep_GetTypeTag", "Game", r"GAME::ConversationStep::GetTypeTag\(void\)"),
    ("ConversationStep_IsAvailable", "Game", r"GAME::ConversationStep::IsAvailable\(void\)"),
    ("ConversationStep_IsUsed", "Game", r"GAME::ConversationStep::IsUsed\(void\)"),
    ("ConversationStep_GetParent", "Game", r"GAME::ConversationStep::GetParent\(void\)"),
    ("ConversationStep_GetSteps", "Game", r"GAME::ConversationStep::GetSteps\(void\)"),
    ("ConversationStep_GetFlags", "Game", r"GAME::ConversationStep::GetFlags\(void\)"),
    ("Character_GetConversation", "Game", r"GAME::Character::GetConversation\(void\)"),
    # ---- review cursor classification (src/world.cpp): the Interact key's own filter ----
    ("FixedActor_GetStaticClassInfo", "Game", r"GAME::FixedActor::GetStaticClassInfo\(void\)"),
    ("Actor_GetStaticClassInfo", "Engine", r"GAME::Actor::GetStaticClassInfo\(void\)"),
    ("Item_GetStaticClassInfo", "Game", r"GAME::Item::GetStaticClassInfo\(void\)"),
    ("FixedActor_IsOfInterest", "Game", r"GAME::FixedActor::IsOfInterest\(void\)"),
    ("Item_IsOfInterest", "Game", r"GAME::Item::IsOfInterest\(void\)"),
    ("FixedActor_vftable", "Game", r"GAME::FixedActor::`vftable'\{for `GAME::Object'\}"),
    ("Monster_vftable", "Game", r"GAME::Monster::`vftable'\{for `GAME::Object'\}"),
    ("Item_vftable", "Game", r"GAME::Item::`vftable'\{for `GAME::Object'\}"),
    ("Npc_HasConversation", "Game", r"GAME::Npc::HasConversation\(void\)"),
    # ---- destructibles (barrels, crates, quest breakables) for the B review group ----
    ("Destructible_GetStaticClassInfo", "Game", r"GAME::Destructible::GetStaticClassInfo\(void\)"),
    ("Destructible_IsBroken", "Game", r"GAME::Destructible::IsBroken\(void\)"),
    ("Destructible_IsTargetable", "Game", r"GAME::Destructible::IsTargetable\(void\)"),
    # ---- camera zoom presets (src/world.cpp) ----
    ("GameCamera_SetZoom", "Game", r"GAME::GameCamera::SetZoom\(float\)"),
    ("GameCamera_ResetZoom", "Game", r"GAME::GameCamera::ResetZoom\(void\)"),
    ("GameCamera_SetCameraYaw", "Game", r"GAME::GameCamera::SetCameraYaw\(float\)"),
    # ---- message boxes (src/exe_ui.cpp): the exported DialogManager behind the exe's prompt box ----
    ("GameEngine_GetDialogManager", "Game", r"GAME::GameEngine::GetDialogManager\(void\)"),
    ("DialogManager_GetNumDialog", "Game", r"GAME::DialogManager::GetNumDialog\(void\)"),
    ("GameEngine_SetLastUsedTeleportId", "Game", r"GAME::GameEngine::SetLastUsedTeleportId\("),
    ("DialogManager_PeekTopDialog", "Game", r"GAME::DialogManager::PeekTopDialog\(void\)"),
    ("DialogManager_AddResponse", "Game", r"GAME::DialogManager::AddResponse\("),
    ("DialogManager_RemoveTopDialog", "Game", r"GAME::DialogManager::RemoveTopDialog\(void\)"),
    # ---- labels (u16 strings by value -> hidden return pointer) ----
    ("Monster_GetGameDescription", "Game", r"GAME::Monster::GetGameDescription\(bool,bool\)"),
    ("Npc_GetRolloverDescription", "Game", r"GAME::Npc::GetRolloverDescription\(void\)"),
    ("Player_GetRolloverDescription", "Game", r"GAME::Player::GetRolloverDescription\(void\)"),
    ("Item_GetGameDescription", "Game", r"GAME::Item::GetGameDescription\(bool,bool\)"),
    ("Object_vftable", "Engine", r"const GAME::Object::`vftable'"),
    ("WorldCamera_Project", "Engine", r"GAME::WorldCamera::Project\("),
    ("WorldCamera_GetRayThroughImagePoint", "Engine", r"GAME::WorldCamera::GetRayThroughImagePoint\("),
    ("World_GetIntersection", "Engine", r"GAME::World::GetIntersection\(class GAME::WorldRay"),
    ("World_GetAllIntersections", "Engine", r"GAME::World::GetAllIntersections\("),
    ("Skill_IsTargetInLOS_Id", "Game", r"GAME::Skill::IsTargetInLOS\(class GAME::Character const & __ptr64,unsigned int\)"),
    ("Skill_IsTargetInLOS_Point", "Game", r"GAME::Skill::IsTargetInLOS\(class GAME::Character const & __ptr64,class GAME::WorldVec3 const"),
    ("Viewport_ctor", "Engine", r"GAME::Viewport::Viewport\(int,int,int,int\)"),
    ("Engine_ProcessUserInput", "Engine", r"GAME::Engine::ProcessUserInput\("),
    ("Display_Render", "Engine", r"GAME::Display::Render\("),
    ("Display_HandleKeyEvent", "Engine", r"GAME::Display::HandleKeyEvent\("),
    ("Display_HandleMouseEvent", "Engine", r"GAME::Display::HandleMouseEvent\("),
    ("ButtonEvent_GetText", "Engine", r"GAME::InputDevice::ButtonEvent::GetText\(void\)"),
    ("InputDevice_GetDefaultButtonName", "Engine", r"GAME::InputDevice::GetDefaultButtonName\("),
    ("DirectInputDevice_GetButtonName", "DirectInput", r"DirectInputDevice::GetButtonName\("),
    ("RenderText2d_XY_C_U16", "Engine", r"RenderText2d\(int,int,class GAME::Color const & __ptr64,unsigned short const \* __ptr64,class GAME::GraphicsFont2"),
    ("RenderText2d_XY_CC_U16", "Engine", r"RenderText2d\(int,int,class GAME::Color const & __ptr64,class GAME::Color const & __ptr64,unsigned short const \*"),
    ("RenderText2d_Rect_C_U16", "Engine", r"RenderText2d\((class|struct) GAME::Rect,class GAME::Color const & __ptr64,unsigned short const \*"),
    ("RenderText2d_Rect_CC_U16", "Engine", r"RenderText2d\((class|struct) GAME::Rect,class GAME::Color const & __ptr64,class GAME::Color const & __ptr64,unsigned short const \*"),
    ("RenderText2d_XY_U16_FontName", "Engine", r"RenderText2d\(int,int,unsigned short const \* __ptr64,class std::basic_string<char,[^)]*__ptr64,float,enum GAME::GraphicsXAlign"),
    ("RenderText2d_XY_U16_FontName2", "Engine", r"RenderText2d\(int,int,unsigned short const \* __ptr64,class std::basic_string<char,[^)]*float,float,enum"),
    ("RenderText2d_Rect_U16_FontName", "Engine", r"RenderText2d\((class|struct) GAME::Rect,unsigned short const \* __ptr64,class std::basic_string<char"),
    ("RenderText2dBox_XY_C_U16_Font", "Engine", r"RenderText2dBox\(int,int,class GAME::Color const & __ptr64,unsigned short const \* __ptr64,class GAME::GraphicsFont2"),
    ("RenderText2dBox_XY_C_U16_FontName", "Engine", r"RenderText2dBox\(int,int,class GAME::Color const & __ptr64,unsigned short const \* __ptr64,class std::basic_string<char"),
    ("RenderColoredText2d_U16", "Engine", r"RenderColoredText2d\(int,int,class std::basic_string<unsigned short"),
    ("RenderText2dParagraph", "Engine", r"RenderText2dParagraph\("),
    ("DirectInputDevice_AllowShortcutKeys", "DirectInput", r"DirectInputDevice::AllowShortcutKeys\(bool\)"),
    ("DirectInputDevice_keyboardHook", "DirectInput", r"DirectInputDevice::keyboardHook$"),
    ("DirectInputDevice_GetNumKeyEvents", "DirectInput", r"DirectInputDevice::GetNumKeyEvents\(void\)"),
    ("DirectInputDevice_GetKeyEvent", "DirectInput", r"DirectInputDevice::GetKeyEvent\(int\)"),
    ("DirectInputDevice_GetNumMouseEvents", "DirectInput", r"DirectInputDevice::GetNumMouseEvents\(void\)"),
    ("ButtonEvent_dtor", "Engine", r"GAME::InputDevice::ButtonEvent::~ButtonEvent\(void\)"),
    ("ButtonEvent_ctor", "Engine", r"GAME::InputDevice::ButtonEvent::ButtonEvent\(void\)"),
    ("MouseEvent_ctor", "Engine", r"GAME::InputDevice::MouseEvent::MouseEvent\(void\)"),
    ("DirectInputDevice_IsButtonDown", "DirectInput", r"DirectInputDevice::IsButtonDown\("),
    ("DirectInputDevice_GetCursorPosition", "DirectInput", r"DirectInputDevice::GetCursorPosition\("),
    ("DirectInputDevice_GetMouseEvent", "DirectInput", r"DirectInputDevice::GetMouseEvent\(int\)"),
    ("DirectInputDevice_keyboardHookRefCount", "DirectInput", r"DirectInputDevice::keyboardHookRefCount$"),
    # ---- the in-world windows' exported model (src/gameapi*.cpp; docs/ingame-ui-survey.md) ----
    ("gGameEngine", "Game", r"^class GAME::GameEngine \* __ptr64 __ptr64 GAME::gGameEngine$"),
    ("LocalizationManager_Instance", "Engine", r"GAME::LocalizationManager::Instance\(void\)"),
    ("ObjectManager_Get", "Engine", r"GAME::Singleton<class GAME::ObjectManager>::Get\(void\)"),
    ("ObjectManager_GetObjectList", "Engine", r"GAME::ObjectManager::GetObjectList\("),
    ("ObjectManager_IsObjectIdOnDeletedList", "Engine", r"GAME::ObjectManager::IsObjectIdOnDeletedList\("),
    ("GameEngine_GetObjectives", "Game", r"GAME::GameEngine::GetObjectives\(void\)"),
    ("Quest2Repository_Get", "Game", r"GAME::Singleton<class GAME::Quest2Repository>::Get\(void\)"),
    ("Quest2Repository_GetQuests", "Game", r"GAME::Quest2Repository::GetQuests\("),
    ("Quest2_GetName", "Game", r"GAME::Quest2::GetName\(void\)"),
    ("Quest2_GetGroup", "Game", r"GAME::Quest2::GetGroup\(void\)"),
    ("Quest2_GetId", "Game", r"GAME::Quest2::GetId\(void\)"),
    ("Quest2_IsTracked", "Game", r"GAME::Quest2::IsTracked\(void\)"),
    ("Quest2_SetTracked", "Game", r"GAME::Quest2::SetTracked\(bool\)"),
    ("Quest2_IsComplete", "Game", r"GAME::Quest2::IsComplete\(bool\)"),
    ("Quest2_InProgress", "Game", r"GAME::Quest2::InProgress\(bool\)"),
    ("Quest2_GetNumTasks", "Game", r"GAME::Quest2::GetNumTasks\(void\)"),
    ("Quest2_GetTaskByIndex", "Game", r"GAME::Quest2::GetTaskByIndex\(int\)"),
    ("Quest2Task_GetName", "Game", r"GAME::Quest2Task::GetName\(void\)"),
    ("Quest2Task_GetDescription", "Game", r"GAME::Quest2Task::GetDescription\(void\)"),
    ("Quest2Task_GetState", "Game", r"GAME::Quest2Task::GetState\(void\)"),
    ("Quest2Task_GetObjectives", "Game", r"GAME::Quest2Task::GetObjectives\(void\)"),
    ("Quest2Task_GetRewards", "Game", r"GAME::Quest2Task::GetRewards\(void\)"),
    ("Quest2Objective_GetText", "Game", r"GAME::Quest2Objective::GetText\("),
    ("Quest2Objective_IsSatisfied", "Game", r"GAME::Quest2Objective::IsSatisfied\(void\)"),
    ("Quest2Event_GetText", "Game", r"GAME::Quest2Event::GetText\("),
    # ---- quest completion + rewards (src/quest_rewards.cpp; docs/ingame-ui-survey.md "Quest reward") ----
    ("Quest2Task_Complete", "Game", r"GAME::Quest2Task::Complete\(bool\)"),
    ("Quest2Task_GetQuest", "Game", r"GAME::Quest2Task::GetQuest\(void\)"),
    ("Quest2Task_GetUid", "Game", r"GAME::Quest2Task::GetUid\(void\)"),
    ("Quest2_GetFileName", "Game", r"GAME::Quest2::GetFileName\(void\)"),
    ("Quest2Repository_CompleteQuestTask", "Game", r"GAME::Quest2Repository::CompleteQuestTask\("),
    ("ScriptableActionCollection_Execute", "Game", r"GAME::ScriptableActionCollection::Execute\("),
    ("ScriptableActionCollection_GetActions", "Game", r"GAME::ScriptableActionCollection::GetActions\(void\)"),
    ("ScriptableAction_IsReward", "Game", r"GAME::ScriptableAction::IsReward\(void\)"),
    ("ScriptableAction_GetType", "Game", r"GAME::ScriptableAction::GetType\(void\)"),
    ("GiveExperience_GetAmount", "Game", r"GAME::ScriptableAction_GiveExperience::GetAmount\(void\)"),
    ("GiveMoney_GetAmount", "Game", r"GAME::ScriptableAction_GiveMoney::GetAmount\(void\)"),
    ("GiveSkillPoint_GetAmount", "Game", r"GAME::ScriptableAction_GiveSkillPoint::GetAmount\(void\)"),
    ("GiveAttribPoint_GetAmount", "Game", r"GAME::ScriptableAction_GiveAttribPoint::GetAmount\(void\)"),
    ("GiveDevotion_GetAmount", "Game", r"GAME::ScriptableAction_GiveDevotion::GetAmount\(void\)"),
    ("GiveLevel_GetAmount", "Game", r"GAME::ScriptableAction_GiveLevel::GetAmount\(void\)"),
    ("GiveTribute_GetAmount", "Game", r"GAME::ScriptableAction_GiveTribute::GetAmount\(void\)"),
    ("GiveFaction_GetAmount", "Game", r"GAME::ScriptableAction_GiveFaction::GetAmount\(void\)"),
    ("GiveFaction_GetFactionTag", "Game", r"GAME::ScriptableAction_GiveFaction::GetFactionTag\(void\)"),
    ("GiveItem_GetNumItems", "Game", r"GAME::ScriptableAction_GiveItem::GetNumItems\(void\)"),
    ("GiveItem_GetInfoItem", "Game", r"GAME::ScriptableAction_GiveItem::GetInfoItem\("),
    ("GiveItem_GetCount", "Game", r"GAME::ScriptableAction_GiveItem::GetCount\(void\)"),
    ("FactionPack_GetFactionFromString", "Game", r"GAME::FactionPack::GetFactionFromString\("),
    ("GiveExperience_vftable", "Game", r"const GAME::ScriptableAction_GiveExperience::`vftable'$"),
    ("GiveMoney_vftable", "Game", r"const GAME::ScriptableAction_GiveMoney::`vftable'$"),
    ("GiveItem_vftable", "Game", r"const GAME::ScriptableAction_GiveItem::`vftable'$"),
    ("GiveRandomItem_vftable", "Game", r"const GAME::ScriptableAction_GiveRandomItem::`vftable'$"),
    ("GiveSkillPoint_vftable", "Game", r"const GAME::ScriptableAction_GiveSkillPoint::`vftable'$"),
    ("GiveAttribPoint_vftable", "Game", r"const GAME::ScriptableAction_GiveAttribPoint::`vftable'$"),
    ("GiveDevotion_vftable", "Game", r"const GAME::ScriptableAction_GiveDevotion::`vftable'$"),
    ("GiveLevel_vftable", "Game", r"const GAME::ScriptableAction_GiveLevel::`vftable'$"),
    ("GiveTribute_vftable", "Game", r"const GAME::ScriptableAction_GiveTribute::`vftable'$"),
    ("Player_GetMarkerUIDs", "Game", r"GAME::Player::GetMarkerUIDs\(void\)"),
    ("Character_GetFactionPack", "Game", r"GAME::Character::GetFactionPack\(void\)const"),
    ("FactionPack_GetFactionTag", "Game", r"GAME::FactionPack::GetFactionTag\("),
    ("FactionPack_GetValue", "Game", r"GAME::FactionPack::GetValue\(enum GAME::FactionType\)"),
    ("FactionPack_IsUnlocked", "Game", r"GAME::FactionPack::IsUnlocked\("),
    ("GameEngine_IsFactionPlayerVisible", "Game", r"GAME::GameEngine::IsFactionPlayerVisible\("),
    ("FactionPack_IsModified", "Game", r"GAME::FactionPack::IsModified\("),
    ("GameEngine_IsStartingFaction", "Game", r"GAME::GameEngine::IsStartingFaction\("),
    ("GameEngine_IsHiddenFaction", "Game", r"GAME::GameEngine::IsHiddenFaction\("),
    ("GameEngine_GetFactionLevelName", "Game", r"GAME::GameEngine::GetFactionLevelName\("),
    ("GameEngine_GetFactionLevelBounds", "Game", r"GAME::GameEngine::GetFactionLevelBounds\("),
    ("GameEngine_FactionValueToLevel", "Game", r"GAME::GameEngine::FactionValueToLevel\("),
    ("Player_GetPlayerHotSlotCtrl", "Game", r"GAME::Player::GetPlayerHotSlotCtrl\(void\)"),
    ("HotSlotCtrl_GetHotSlotOption", "Game", r"GAME::PlayerHotSlotCtrl::GetHotSlotOption\("),
    ("HotSlotCtrl_GetSlotStatus", "Game", r"GAME::PlayerHotSlotCtrl::GetSlotStatus\("),
    ("HotSlotCtrl_GetPrimarySlot", "Game", r"GAME::PlayerHotSlotCtrl::GetPrimarySlot\(void\)"),
    ("HotSlotCtrl_GetSecondarySlot", "Game", r"GAME::PlayerHotSlotCtrl::GetSecondarySlot\(void\)"),
    ("HotSlotCtrl_GetHealthPotionSlot", "Game", r"GAME::PlayerHotSlotCtrl::GetHealthPotionSlot\(void\)"),
    ("HotSlotCtrl_GetManaPotionSlot", "Game", r"GAME::PlayerHotSlotCtrl::GetManaPotionSlot\(void\)"),
    ("HotSlotCtrl_SetHotSlot", "Game", r"GAME::PlayerHotSlotCtrl::SetHotSlot\(unsigned int,class"),
    ("HotSlotCtrl_SetPrimarySkillId", "Game", r"GAME::PlayerHotSlotCtrl::SetPrimarySkillId\("),
    ("HotSlotCtrl_SetSecondarySkillId", "Game", r"GAME::PlayerHotSlotCtrl::SetSecondarySkillId\("),
    ("HotSlotCtrl_GetDisplayedSkillSetIndex", "Game", r"GAME::PlayerHotSlotCtrl::GetDisplayedSkillSetIndex\("),
    ("HotSlotCtrl_ActivateHotSlot", "Game", r"GAME::PlayerHotSlotCtrl::ActivateHotSlot\("),
    ("HotSlotOption_GetDisplayName", "Game", r"GAME::HotSlotOption::GetDisplayName\("),
    ("HotSlotOption_GetRolloverText", "Game", r"GAME::HotSlotOption::GetRolloverText\("),
    ("HotSlotOption_GetType", "Game", r"GAME::HotSlotOption::GetType\(void\)"),
    ("HotSlotOption_GetSkillId", "Game", r"GAME::HotSlotOption::GetSkillId\(void\)"),
    ("HotSlotOption_GetCooldownRemaining", "Game", r"GAME::HotSlotOption::GetCooldownRemaining\(void\)"),
    ("HotSlotOption_SetPlayer", "Game", r"GAME::HotSlotOption::SetPlayer\("),
    ("HotSlotOption_vftable", "Game", r"const GAME::HotSlotOption::`vftable'$"),
    ("HotSlotOptionSkill_ctor", "Game", r"GAME::HotSlotOptionSkill::HotSlotOptionSkill\(unsigned int\)"),
    ("HotSlotOptionSkill_vftable", "Game", r"const GAME::HotSlotOptionSkill::`vftable'$"),
    ("HotSlotOptionSkill_GetCooldownRemaining", "Game", r"GAME::HotSlotOptionSkill::GetCooldownRemaining\(void\)"),
    ("Player_GetLoreCodex", "Game", r"GAME::Player::GetLoreCodex\(void\)"),
    ("ItemNote_GetCodexTitleTag", "Game", r"GAME::ItemNote::GetCodexTitleTag\(void\)"),
    ("Item_GetItemTextTag", "Game", r"GAME::Item::GetItemTextTag\(void\)"),
    ("ItemNote_GetCodexSubHeadingTag", "Game", r"GAME::ItemNote::GetCodexSubHeadingTag\(void\)"),
    # inventory / equipment / items
    ("ControllerPlayer_GetInventoryCtrl", "Game", r"GAME::ControllerPlayer::GetInventoryCtrl\(void\)const"),
    ("InvCtrl_GetNumberOfSacks", "Game", r"GAME::PlayerInventoryCtrl::GetNumberOfSacks\("),
    ("InvCtrl_GetSelectedSackNumber", "Game", r"GAME::PlayerInventoryCtrl::GetSelectedSackNumber\("),
    ("InvCtrl_SetSelectedSackNumber", "Game", r"GAME::PlayerInventoryCtrl::SetSelectedSackNumber\("),
    ("InvCtrl_GetSack", "Game", r"GAME::PlayerInventoryCtrl::GetSack\(int\)"),
    ("InvCtrl_UseItem", "Game", r"GAME::PlayerInventoryCtrl::UseItem\("),
    ("InvCtrl_RemoveItem", "Game", r"GAME::PlayerInventoryCtrl::RemoveItem\(unsigned int,bool\)"),
    ("InventorySack_GetInventory", "Game", r"GAME::InventorySack::GetInventory\(void\)const"),
    ("InventorySack_GetGridWidth", "Game", r"GAME::InventorySack::GetGridWidth\("),
    ("InventorySack_GetGridHeight", "Game", r"GAME::InventorySack::GetGridHeight\("),
    ("InventorySack_GetButtonName", "Game", r"GAME::InventorySack::GetButtonName\("),
    ("ControllerCharacter_GetEquipmentCtrl", "Game", r"GAME::ControllerCharacter::GetEquipmentCtrl\(void\)const"),
    ("EquipmentCtrl_GetItemId", "Game", r"GAME::EquipmentCtrl::GetItemId\(enum"),
    ("EquipmentCtrl_GetEquipmentLocationTag", "Game", r"GAME::EquipmentCtrl::GetEquipmentLocationTag\("),
    ("EquipmentCtrl_GetIsAlternate", "Game", r"GAME::EquipmentCtrl::GetIsAlternate\("),
    ("EquipmentCtrl_PlaceItem", "Game", r"GAME::EquipmentCtrl::PlaceItem\(enum"),
    ("EquipmentCtrl_RemoveItem", "Game", r"GAME::EquipmentCtrl::RemoveItem\("),
    # two-weapon-set swap on the controller (the two hands only). CanItemBePlaced is already defined below.
    ("ControllerCharacter_GetAlternateEquipment", "Game", r"GAME::ControllerCharacter::GetAlternateEquipment\(void\)"),
    ("ControllerCharacter_SetAlternateEquipment", "Game", r"GAME::ControllerCharacter::SetAlternateEquipment\(bool\)"),
    ("Character_GetCurrentMoney", "Game", r"GAME::Character::GetCurrentMoney\("),
    ("Character_AddMoney", "Game", r"GAME::Character::AddMoney\("),
    ("ControllerPlayer_UseItem", "Game", r"GAME::ControllerPlayer::UseItem\(unsigned int,enum"),
    # attach a component/augment to an item (a pure inventory op, no blacksmith). Character::UseItemOn looks up
    # both items by id, is-a-checks the used item (ItemRelic/ItemEnchantment) and applies it. GetCompatibleItems
    # enumerates every item (bags + equipped + both stashes + the reagent slot) a given component can attach to.
    ("Player_GetCompatibleItems", "Game", r"GAME::Player::GetCompatibleItems\("),
    ("Character_UseItemOn", "Game", r"GAME::Character::UseItemOn\("),
    ("ControllerCharacter_SendDropItemRandom", "Game", r"GAME::ControllerCharacter::SendDropItemRandom\("),
    ("Item_GetUIDisplayText", "Game", r"GAME::Item::GetUIDisplayText\("),
    ("Item_GetSimpleUIDisplayText", "Game", r"GAME::Item::GetSimpleUIDisplayText\("),
    ("Item_GetStackSize", "Game", r"GAME::Item::GetStackSize\(void\)"),
    ("Item_GetItemClassification", "Game", r"GAME::Item::GetItemClassification\(bool\)"),
    ("GameEngine_GetItemColorText", "Game", r"GAME::GameEngine::GetItemColorText\("),
    ("Item_AreRequirementsMet", "Game", r"GAME::Item::AreRequirementsMet\(class GAME::Character const"),
    ("Item_GetLevelRequirement", "Game", r"GAME::Item::GetLevelRequirement\(void\)"),
    # The equip gate's numbers (docs/ingame-ui-survey.md "Requirements"): the virtual requirement getters (ItemEquipment
    # overrides; dispatched by slot), the game's own reduced-requirement compare, and the per-slot attached flag
    ("Item_GetStrengthRequirement", "Game", r"GAME::Item::GetStrengthRequirement\(void\)"),
    ("Item_GetDexterityRequirement", "Game", r"GAME::Item::GetDexterityRequirement\(void\)"),
    ("Item_GetIntelligenceRequirement", "Game", r"GAME::Item::GetIntelligenceRequirement\(void\)"),
    ("Item_MeetsRequirements", "Game", r"GAME::Item::MeetsRequirements\(float,float,float\)"),
    ("EquipmentCtrl_IsItemAttached", "Game", r"GAME::EquipmentCtrl::IsItemAttached\(unsigned int\)"),
    ("Item_vftable_plain", "Game", r"const GAME::Item::`vftable'$"),
    ("GameEngine_GetItemMaxStackSize", "Game", r"GAME::GameEngine::GetItemMaxStackSize\("),
    # Stack split, as the exe's stack-split window's OK does (exe+0x1dcb70, read 2026-08-26): clone the item
    # from a copy of its ItemReplicaInfo (inline at Item+0x538, 0x190 bytes; +0 object id -> 0 = allocate,
    # +0x178 = count) with Item::CreateItem, shrink the source with SetStackSize + SendUpdateItemStack; the
    # cursor part of the handler reduces to SendAddItemToInventory. DestroyObjectEx undoes a clone with no room.
    ("Item_CreateItem", "Game", r"GAME::Item::CreateItem\(struct GAME::ItemReplicaInfo const"),
    ("Item_SetStackSize", "Game", r"GAME::Item::SetStackSize\(unsigned int\)"),
    ("ControllerCharacter_SendUpdateItemStack", "Game", r"GAME::ControllerCharacter::SendUpdateItemStack\("),
    ("ObjectManager_DestroyObjectEx", "Engine", r"GAME::ObjectManager::DestroyObjectEx\("),
    ("GameEngine_GetMarketInventorySack", "Game", r"GAME::GameEngine::GetMarketInventorySack\(unsigned int,enum GAME::Market_TypeEnum\)const"),
    ("GameEngine_GetMarketItemStatus", "Game", r"GAME::GameEngine::GetMarketItemStatus\("),
    ("GameEngine_PlayerPurchaseRequest", "Game", r"GAME::GameEngine::PlayerPurchaseRequest\("),
    ("GameEngine_CreateUIPlayerBuyText", "Game", r"GAME::GameEngine::CreateUIPlayerBuyText\("),
    ("GameEngine_CreateUIPlayerSellText", "Game", r"GAME::GameEngine::CreateUIPlayerSellText\("),
    ("Player_GetPrivateStash", "Game", r"GAME::Player::GetPrivateStash\(void\)"),
    ("GameEngine_GetPlayerTransfer", "Game", r"GAME::GameEngine::GetPlayerTransfer\(void\)"),
    # skills
    ("Character_GetSkillManager", "Game", r"GAME::Character::GetSkillManager\(void\)const"),
    ("SkillManager_GetSkillList", "Game", r"GAME::SkillManager::GetSkillList\(void\)"),
    ("SkillManager_GetUISkillList", "Game", r"GAME::SkillManager::GetUISkillList\(void\)"),
    ("SkillManager_GetSkillMasteryIds", "Game", r"GAME::SkillManager::GetSkillMasteryIds\("),
    ("SkillManager_IncrementSkill", "Game", r"GAME::SkillManager::IncrementSkill\(unsigned int,unsigned int\)"),
    ("SkillManager_RecalculateSkills", "Game", r"GAME::SkillManager::RecalculateSkills\("),
    ("SkillManager_UseReclamationPoints", "Game", r"GAME::SkillManager::UseReclamationPoints\("),
    ("SkillManager_GetCurrentSkillReclamationCost", "Game", r"GAME::SkillManager::GetCurrentSkillReclamationCost\("),
    ("SkillManager_GetNumMasteryPoints", "Game", r"GAME::SkillManager::GetNumMasteryPoints\("),
    ("SkillManager_AddExperience", "Game", r"GAME::SkillManager::AddExperience\(unsigned int\)"),
    ("Skill_GetSkillLevel", "Game", r"GAME::Skill::GetSkillLevel\(void\)"),
    ("Skill_GetMaxLevel", "Game", r"GAME::Skill::GetMaxLevel\(void\)"),
    ("Skill_GetUltimateLevel", "Game", r"GAME::Skill::GetUltimateLevel\(void\)"),
    ("Skill_GetMasteryId", "Game", r"GAME::Skill::GetMasteryId\(void\)"),
    ("Skill_GetMasteryLevel", "Game", r"GAME::Skill::GetMasteryLevel\(void\)"),
    ("Skill_GetMasteryLevelRequirement", "Game", r"GAME::Skill::GetMasteryLevelRequirement\("),
    ("Skill_GetModifiers", "Game", r"GAME::Skill::GetModifiers\(void\)"),   # a base skill's modifier skill ids (reverse-mapped)
    ("Skill_GetSecondarySkills", "Game", r"GAME::Skill::GetSecondarySkills\(void\)"),   # a base skill's secondary sub-skill ids (pet modifiers live here)
    ("Skill_IsBaseSkillEnabled", "Game", r"GAME::Skill::IsBaseSkillEnabled\("),   # the game's own learn gate for a sub-skill
    ("Skill_IsSecondary", "Game", r"GAME::Skill::IsSecondary\(void\)"),
    ("Skill_IsLocked", "Game", r"GAME::Skill::IsLocked\(void\)"),
    ("Skill_IsSkillTheMasterySkill", "Game", r"GAME::Skill::IsSkillTheMasterySkill\("),
    ("Skill_IsSkillModifier", "Game", r"GAME::Skill::IsSkillModifier\("),
    ("Skill_IsSkillEnabled", "Game", r"GAME::Skill::IsSkillEnabled\("),
    ("Skill_CreateUISkillName", "Game", r"GAME::Skill::CreateUISkillName\(bool\)"),
    ("Skill_GetDisplayNameTag", "Game", r"GAME::Skill::GetDisplayNameTag\("),
    ("Skill_GetBaseSkills", "Game", r"GAME::Skill::GetBaseSkills\("),
    ("Skill_GetSkillProfile", "Game", r"GAME::Skill::GetSkillProfile\(void\)"),
    ("SkillProfile_GetSkillTier", "Game", r"GAME::SkillProfile::GetSkillTier\("),
    ("Skill_IncrementSkillLevel", "Game", r"GAME::Skill::IncrementSkillLevel\("),
    ("Skill_DecrementSkillLevel", "Game", r"GAME::Skill::DecrementSkillLevel\("),
    ("Skill_vftable", "Game", r"const GAME::Skill::`vftable'$"),
    ("Skill_Mastery_GetStaticClassInfo", "Game", r"GAME::Skill_Mastery::GetStaticClassInfo\("),
    ("Skill_GetStaticClassInfo", "Game", r"GAME::Skill::GetStaticClassInfo\("),
    # A skill's targeting: SkillActivated::GetTargetType returns *(int*)(this+0x5c0), the SkillTargetType enum
    # {Default=0, Point=1, Object=2, Target=3} loaded from the DBR targetingMode. The base impl is never
    # overridden (only SkillActivated defines it), so it can be called directly on any SkillActivated object;
    # guard with is-a SkillActivated first (passives/modifiers are Skill but not SkillActivated).
    ("SkillActivated_GetTargetType", "Game", r"GAME::SkillActivated::GetTargetType\(void\)"),
    ("SkillActivated_GetStaticClassInfo", "Game", r"GAME::SkillActivated::GetStaticClassInfo\(void\)"),
    # The game's own default-skill accessor: GetDefaultSkillId(DefaultSkill) searches the character's live
    # skill list for the default action of a role (0 = left mouse basic attack, 1 = right mouse), so the id is
    # per-character and weapon-dependent -- never cache it. Used to restore the mouse buttons to basic attack.
    ("SkillManager_GetDefaultSkillId", "Game", r"GAME::SkillManager::GetDefaultSkillId\(enum GAME::DefaultSkill\)"),
    # Resolve a buff/debuff entry's record path (SkillBuffTransfer+0x00) to the live skill id, to name it (the
    # entry holds no skill id -- +0x48 is the caster). The char const* overload takes the record path directly.
    ("SkillManager_FindSkillId", "Game", r"GAME::SkillManager::FindSkillId\(char const"),
    # skills granted by equipped items (the hotbar-manager palette includes these)
    ("SkillManager_GetItemSkillList", "Game", r"GAME::SkillManager::GetItemSkillList\(void\)"),
    # per-item granted skill: FindItemSkillIdByItemId(item id) -- used to source the palette from EQUIPPED items
    # only (GetItemSkillList also returns loose bag components' skills, e.g. a Chilled Steel granting Ice Spike).
    ("SkillManager_FindItemSkillIdByItemId", "Game", r"GAME::SkillManager::FindItemSkillIdByItemId\(unsigned int\)"),
    # a proc / chance-on-attack item skill (Ice Spike from a component) is auto-triggered, not assignable
    ("Skill_IsItemSkillAuto", "Game", r"GAME::Skill::IsItemSkillAuto\(void\)"),
    # the exe's quickbar-picker filter (exe+0x1e7860): learned, primary or secondary, not auto-toggled, and on the
    # displayed skill set unless it is a global, non-sub skill
    ("Skill_IsPrimary", "Game", r"GAME::Skill::IsPrimary\(void\)"),
    ("Skill_GetSkillSet", "Game", r"GAME::Skill::GetSkillSet\(void\)"),
    ("Skill_GetSubSkillParentId", "Game", r"GAME::Skill::GetSubSkillParentId\(void\)"),
    ("SkillManager_IsGlobalSkillTypeAndAllowed", "Game", r"GAME::SkillManager::IsGlobalSkillTypeAndAllowed\("),
    ("SkillActivatedBuffSelf_IsAutoToggle", "Game", r"GAME::SkillActivatedBuffSelf::IsAutoToggle\(void\)"),   # Skill vtable +0x610; base is a folded return-false
    ("SkillActivatedBuffSelf_vftable", "Game", r"const GAME::SkillActivatedBuffSelf::`vftable'$"),
    # the skills window's SkillReasons builder (exe+0x2492b0) -> GenerateUISkillText's requirement lines
    ("Skill_IsAugmented", "Game", r"GAME::Skill::IsAugmented\(void\)"),
    ("Skill_GetAugmentedLevel", "Game", r"GAME::Skill::GetAugmentedLevel\(void\)"),
    ("SkillProfile_IsExclusiveSkill", "Game", r"GAME::SkillProfile::IsExclusiveSkill\(void\)"),
    ("Skill_GetSkillDependancies", "Game", r"GAME::Skill::GetSkillDependancies\("),
    ("Skill_Mastery_GetEnumeration", "Game", r"GAME::Skill_Mastery::GetEnumeration\(void\)"),
    ("Character_GetSkillMasteriesActive", "Game", r"GAME::Character::GetSkillMasteriesActive\("),
    ("Character_GetSkillPoints", "Game", r"GAME::Character::GetSkillPoints\(void\)"),
    ("Character_SubtractSkillPoint", "Game", r"GAME::Character::SubtractSkillPoint\("),
    ("Character_AddSkillPoints", "Game", r"GAME::Character::AddSkillPoints\("),
    ("Character_GetSkillMasteries", "Game", r"GAME::Character::GetSkillMasteries\(class"),
    ("Character_GetSkillMasteriesAllowed", "Game", r"GAME::Character::GetSkillMasteriesAllowed\("),
    ("SkillManager_UpdateMasteriesAllowed", "Game", r"GAME::SkillManager::UpdateMasteriesAllowed\("),
    ("GameEngine_GenerateUISkillText", "Game", r"GAME::GameEngine::GenerateUISkillText\("),
    # character sheet
    ("Character_GetCharLevel", "Game", r"GAME::Character::GetCharLevel\(void\)"),
    ("Character_GetExperiencePoints", "Game", r"GAME::Character::GetExperiencePoints\("),
    ("Character_GetNextLevelExperience", "Game", r"GAME::Character::GetNextLevelExperience\("),
    ("Character_GetModifierPoints", "Game", r"GAME::Character::GetModifierPoints\("),
    ("Character_GetTotalCharAttribute", "Game", r"GAME::Character::GetTotalCharAttribute\("),
    ("Character_GetAllDefenseAttributes", "Game", r"GAME::Character::GetAllDefenseAttributes\("),
    ("CombatAttributeAccumulator_ctor", "Game", r"GAME::CombatAttributeAccumulator::CombatAttributeAccumulator\(void\)"),
    ("CombatAttributeAccumulator_dtor", "Game", r"GAME::CombatAttributeAccumulator::~CombatAttributeAccumulator\(void\)"),
    ("CombatAttributeAccumulator_GetDefense", "Game", r"GAME::CombatAttributeAccumulator::GetDefense\(void\)"),
    ("Character_GetCombatManager", "Game", r"GAME::Character::GetCombatManager\(void\)const"),
    ("CombatManager_DesignerCalculateOffensiveAbility", "Game", r"GAME::CombatManager::DesignerCalculateOffensiveAbility\("),
    ("CombatManager_DesignerCalculateDefensiveAbility", "Game", r"GAME::CombatManager::DesignerCalculateDefensiveAbility\("),
    ("Player_CalculateDps", "Game", r"GAME::Player::CalculateDps\("),
    ("Player_GetClassNameA", "Game", r"GAME::Player::GetClassNameA\("),
    ("Character_GetDevotionPoints", "Game", r"GAME::Character::GetDevotionPoints\("),
    # ---- devotion (src/gameapi_devotion.cpp; docs/devotion.md) ----
    ("Character_GetTotalDevotionPoints", "Game", r"GAME::Character::GetTotalDevotionPoints\("),
    ("Character_GetMaxDevotionPoints", "Game", r"GAME::Character::GetMaxDevotionPoints\("),
    ("Character_SubtractDevotionPoint", "Game", r"GAME::Character::SubtractDevotionPoint\("),
    ("Character_AddDevotionPoints", "Game", r"GAME::Character::AddDevotionPoints\("),
    ("Character_AddTotalDevotionPoints", "Game", r"GAME::Character::AddTotalDevotionPoints\("),
    ("Character_GetAffinity", "Game", r"GAME::Character::GetAffinity\("),
    ("Character_AddAffinity", "Game", r"GAME::Character::AddAffinity\("),
    ("Character_SubtractAffinity", "Game", r"GAME::Character::SubtractAffinity\("),
    ("Character_GetSkillList", "Game", r"GAME::Character::GetSkillList\("),
    ("Character_GetItemSkillList", "Game", r"GAME::Character::GetItemSkillList\("),
    ("Character_GetItemSkillCache", "Game", r"GAME::Character::GetItemSkillCache\("),
    ("Skill_GetDevotionLevel", "Game", r"GAME::Skill::GetDevotionLevel\("),
    ("Skill_GetDevotionMaxLevel", "Game", r"GAME::Skill::GetDevotionMaxLevel\("),
    ("Skill_GetDevotionExperience", "Game", r"GAME::Skill::GetDevotionExperience\("),
    ("Skill_GetRequiredExperience", "Game", r"GAME::Skill::GetRequiredExperience\("),
    ("Skill_GetDevotionParent", "Game", r"GAME::Skill::GetDevotionParent\("),
    ("Skill_SetDevotionParent", "Game", r"GAME::Skill::SetDevotionParent\("),
    ("Skill_IncrementDevotionLevel", "Game", r"GAME::Skill::IncrementDevotionLevel\("),
    ("Skill_SetSkillLevel", "Game", r"GAME::Skill::SetSkillLevel\("),
    ("Skill_SetAutocastSkill", "Game", r"GAME::Skill::SetAutocastSkill\("),
    ("Skill_GetTemplateAutoCast", "Game", r"GAME::Skill::GetTemplateAutoCast\("),
    ("Skill_GetAutoCastSkill", "Game", r"GAME::Skill::GetAutoCastSkill\("),
    ("Skill_HasAutocastSkill", "Game", r"GAME::Skill::HasAutocastSkill\("),
    ("Skill_HasAutocastInDbr", "Game", r"GAME::Skill::HasAutocastInDbr\("),
    ("Skill_GetSkillOperation", "Game", r"GAME::Skill::GetSkillOperation\("),
    ("Skill_IsSkillA", "Game", r"GAME::Skill::IsSkillA\("),
    ("Skill_IsSkillBlackListed", "Game", r"GAME::Skill::IsSkillBlackListed\("),
    ("Skill_GetSkillState", "Game", r"GAME::Skill::GetSkillState\("),
    ("SkillManager_IsDefaultSkill", "Game", r"GAME::SkillManager::IsDefaultSkill\("),
    ("SkillManager_GetNumDevotionPointsSpent", "Game", r"GAME::SkillManager::GetNumDevotionPointsSpent\("),
    ("GameEngine_GenerateUIDevotionText", "Game", r"GAME::GameEngine::GenerateUIDevotionText\("),
    ("SkillManager_GetCurrentDevotionReclamationCost", "Game", r"GAME::SkillManager::GetCurrentDevotionReclamationCost\("),
    ("SkillManager_GetDevotionReclamationAetherCost", "Game", r"GAME::SkillManager::GetDevotionReclamationAetherCost\("),
    ("SkillManager_UseDevotionReclamationPoints", "Game", r"GAME::SkillManager::UseDevotionReclamationPoints\("),
    ("Player_GetCurrentAether", "Game", r"GAME::Player::GetCurrentAether\("),
    ("Player_AddAether", "Game", r"GAME::Player::AddAether\("),
    ("Skill_GetCurrentLevel", "Game", r"GAME::Skill::GetCurrentLevel\("),
    # shrines, achievements, party, loot filter
    ("StaticShrine_GetStaticClassInfo", "Game", r"GAME::StaticShrine::GetStaticClassInfo\("),
    ("StaticShrine_IsCleansed", "Game", r"GAME::StaticShrine::IsCleansed\("),
    ("StaticShrine_GetDevotionPoints", "Game", r"GAME::StaticShrine::GetDevotionPoints\("),
    ("StaticShrine_GetOffering1DisplayName", "Game", r"GAME::StaticShrine::GetOffering1DisplayName\("),
    ("StaticShrine_GetOffering2DisplayName", "Game", r"GAME::StaticShrine::GetOffering2DisplayName\("),
    ("StaticShrine_GetOffering3DisplayName", "Game", r"GAME::StaticShrine::GetOffering3DisplayName\("),
    ("GameEngine_GetAchievementManager", "Game", r"GAME::GameEngine::GetAchievementManager\("),
    ("AchievementManager_GetGroups", "Game", r"GAME::AchievementManager::GetGroups\("),
    ("Achievement_GetTitle", "Game", r"GAME::Achievement::GetTitle\("),
    ("Achievement_GetDescription", "Game", r"GAME::Achievement::GetDescription\("),
    ("Achievement_IsUnlocked", "Game", r"GAME::Achievement::IsUnlocked\("),
    ("Player_GetLootFilter", "Game", r"GAME::Player::GetLootFilter\("),
    ("Player_SetLootFilter", "Game", r"GAME::Player::SetLootFilter\(enum"),
    # loot filter (docs/loot-filter.md): the defaults reset, the game's own pass/hide predicate, the entity
    # visibility a collected placed quest item is hidden by, and the expansion-3 check that adds option 39
    ("Player_SetLootFilterDefaults", "Game", r"GAME::Player::SetLootFilterDefaults\(void\)"),
    ("Item_PassLootFilter", "Game", r"GAME::Item::PassLootFilter\("),
    ("Entity_GetVisibility", "Engine", r"GAME::Entity::GetVisibility\(void\)"),
    ("Engine_IsExpansion3Loaded", "Engine", r"GAME::Engine::IsExpansion3Loaded\(void\)"),
    # character sheet / attribute points / dev experience (docs/ingame-ui-survey.md, the 2026-08-22 exe readout)
    ("Character_DesignerCalculateOffensiveAbility", "Game", r"GAME::Character::DesignerCalculateOffensiveAbility\(float\)"),
    ("Character_DesignerCalculateDefensiveAbility", "Game", r"GAME::Character::DesignerCalculateDefensiveAbility\(float\)"),
    ("ControllerCharacter_IncrementCharacterStrength", "Game", r"GAME::ControllerCharacter::IncrementCharacterStrength\(void\)"),
    ("ControllerCharacter_IncrementCharacterDexterity", "Game", r"GAME::ControllerCharacter::IncrementCharacterDexterity\(void\)"),
    ("ControllerCharacter_IncrementCharacterIntelligence", "Game", r"GAME::ControllerCharacter::IncrementCharacterIntelligence\(void\)"),
    ("ControllerCharacter_IncrementCharacterLife", "Game", r"GAME::ControllerCharacter::IncrementCharacterLife\(int\)"),
    ("ControllerCharacter_IncrementCharacterMana", "Game", r"GAME::ControllerCharacter::IncrementCharacterMana\(void\)"),
    ("Character_GetStrengthLifeIncrement", "Game", r"GAME::Character::GetStrengthLifeIncrement\(void\)"),
    ("Character_GetDexterityLifeIncrement", "Game", r"GAME::Character::GetDexterityLifeIncrement\(void\)"),
    ("Character_GetIntelligenceLifeIncrement", "Game", r"GAME::Character::GetIntelligenceLifeIncrement\(void\)"),
    ("CombatAttributeAccumulator_GetTotalDefenseType", "Game", r"GAME::CombatAttributeAccumulator::GetTotalDefenseType\("),
    ("CombatAttributeAccumulator_GetTotalDefenseModifierType", "Game", r"GAME::CombatAttributeAccumulator::GetTotalDefenseModifierType\("),
    ("CombatDisplayAccumulator_ctor", "Game", r"GAME::CombatDisplayAccumulator::CombatDisplayAccumulator\(bool\)"),
    ("CombatDisplayAccumulator_dtor", "Game", r"GAME::CombatDisplayAccumulator::~CombatDisplayAccumulator\("),
    ("Character_GetAttachedItems", "Game", r"GAME::Character::GetAttachedItems\("),
    ("Character_GetCombatRegionChance", "Game", r"GAME::Character::GetCombatRegionChance\("),
    ("Item_GetDefenseAttributes", "Game", r"GAME::Item::GetDefenseAttributes\("),
    ("ItemEquipment_GetDefenseAttributes", "Game", r"GAME::ItemEquipment::GetDefenseAttributes\("),
    ("ItemArtifact_GetDefenseAttributes", "Game", r"GAME::ItemArtifact::GetDefenseAttributes\("),
    ("ItemRelic_GetDefenseAttributes", "Game", r"GAME::ItemRelic::GetDefenseAttributes\("),
    ("ItemEnchantment_GetDefenseAttributes", "Game", r"GAME::ItemEnchantment::GetDefenseAttributes\("),
    ("CombatAttributeAccumulator_Clear", "Game", r"GAME::CombatAttributeAccumulator::Clear\(void\)"),
    ("GameEngine_CharacterExperienceOutbound", "Game", r"GAME::GameEngine::CharacterExperienceOutbound\("),
    ("GameEngine_DisplaySkillReallocationWindow", "Game", r"GAME::GameEngine::DisplaySkillReallocationWindow\("),
    ("GameEngine_DisplayCrafterWindow", "Game", r"GAME::GameEngine::DisplayCrafterWindow\("),
    ("GameEngine_DisplayEnchanterWindow", "Game", r"GAME::GameEngine::DisplayEnchanterWindow\("),
    # the Inventor (enchanter) window, docs/inventor.md: what its panels and the exe's chamber drop call
    ("ItemEquipment_HasEnchantment", "Game", r"GAME::ItemEquipment::HasEnchantment\(void\)"),
    ("ControllerPlayer_GiveItemToPlayer", "Game", r"GAME::ControllerPlayer::GiveItemToPlayer\("),
    ("Player_GetCurrentDynamite", "Game", r"GAME::Player::GetCurrentDynamite\(void\)"),
    ("GameEngine_MainPlayerCanUseDismantle", "Game", r"GAME::GameEngine::MainPlayerCanUseDismantle\(void\)"),
    ("Item_GetItemCost", "Game", r"GAME::Item::GetItemCost\(bool\)"),            # virtual: the base body, used to find the slot
    ("Item_GetItemLevel", "Game", r"GAME::Item::GetItemLevel\(void\)"),
    ("ItemEquipment_GetRelic", "Game", r"GAME::ItemEquipment::GetRelic\(void\)"),
    ("GameEngine_DisplayTransmutesWindow", "Game", r"GAME::GameEngine::DisplayTransmutesWindow\("),
    ("GameEngine_DisplayItemAscensionWindow", "Game", r"GAME::GameEngine::DisplayItemAscensionWindow\("),
    # crafting (docs/crafting.md): the formula getters the crafting window itself calls
    ("ItemArtifactFormula_GetArtifact", "Game", r"GAME::ItemArtifactFormula::GetArtifact\(void\)"),
    ("ItemArtifactFormula_GetCreationCost", "Game", r"GAME::ItemArtifactFormula::GetCreationCost\("),
    ("ItemArtifactFormula_GetMaximumCraftable", "Game", r"GAME::ItemArtifactFormula::GetMaximumCraftable\("),
    ("Item_GetDropClassification", "Game", r"GAME::Item::GetDropClassification\("),
    # the blacksmith's bonus blurb: the crafter's table record -> a LootRandomizerTable object -> its affix entries,
    # each rendered by the game's own AttributeRange text (what the window's crafter rollover shows)
    ("NpcCrafter_GetEnhancementTableName", "Game", r"GAME::NpcCrafter::GetEnhancementTableName\(void\)"),
    ("NpcCrafter_GetEnhancementTags", "Game", r"GAME::NpcCrafter::GetEnhancementTags\(void\)"),
    ("ObjectManager_CreateObjectFromFile", "Engine", r"GAME::ObjectManager::CreateObjectFromFile\("),
    ("LootRandomizerTable_GetAllEntries", "Game", r"GAME::LootRandomizerTable::GetAllEntries\("),
    ("LootRandomizerTable_GetStaticClassInfo", "Game", r"GAME::LootRandomizerTable::GetStaticClassInfo\("),
    ("AttributeRange_ctor", "Game", r"GAME::AttributeRange::AttributeRange\(void\)"),
    ("AttributeRange_dtor", "Game", r"GAME::AttributeRange::~AttributeRange\(void\)"),
    ("AttributeRange_LoadAffix", "Game", r"GAME::AttributeRange::LoadAffix\("),
    ("AttributeRange_CreateText", "Game", r"GAME::AttributeRange::CreateText\("),
    ("Player_GiveArtifactToCharacter", "Game", r"GAME::Player::GiveArtifactToCharacter\("),   # hooked: the crafted item landing in the bag
    ("ItemArtifactFormula_GetReagentBaseId", "Game", r"GAME::ItemArtifactFormula::GetReagentBaseId\(void\)"),
    ("ItemArtifactFormula_GetReagentBaseDisplayName", "Game", r"GAME::ItemArtifactFormula::GetReagentBaseDisplayName\(bool\)"),
    ("ItemArtifactFormula_GetReagentBaseQuantityForFormula", "Game", r"GAME::ItemArtifactFormula::GetReagentBaseQuantityForFormula\(void\)"),
    ("ItemArtifactFormula_GetReagentBaseCount", "Game", r"GAME::ItemArtifactFormula::GetReagentBaseCount\(class GAME::Character const"),
    ("ItemArtifactFormula_GetReagent1Id", "Game", r"GAME::ItemArtifactFormula::GetReagent1Id\(void\)"),
    ("ItemArtifactFormula_GetReagent1DisplayName", "Game", r"GAME::ItemArtifactFormula::GetReagent1DisplayName\(bool\)"),
    ("ItemArtifactFormula_GetReagent1QuantityForFormula", "Game", r"GAME::ItemArtifactFormula::GetReagent1QuantityForFormula\(void\)"),
    ("ItemArtifactFormula_GetReagent1Count", "Game", r"GAME::ItemArtifactFormula::GetReagent1Count\(class GAME::Character const"),
    ("ItemArtifactFormula_GetReagent2Id", "Game", r"GAME::ItemArtifactFormula::GetReagent2Id\(void\)"),
    ("ItemArtifactFormula_GetReagent2DisplayName", "Game", r"GAME::ItemArtifactFormula::GetReagent2DisplayName\(bool\)"),
    ("ItemArtifactFormula_GetReagent2QuantityForFormula", "Game", r"GAME::ItemArtifactFormula::GetReagent2QuantityForFormula\(void\)"),
    ("ItemArtifactFormula_GetReagent2Count", "Game", r"GAME::ItemArtifactFormula::GetReagent2Count\(class GAME::Character const"),
    ("ItemArtifactFormula_GetReagent3Id", "Game", r"GAME::ItemArtifactFormula::GetReagent3Id\(void\)"),
    ("ItemArtifactFormula_GetReagent3DisplayName", "Game", r"GAME::ItemArtifactFormula::GetReagent3DisplayName\(bool\)"),
    ("ItemArtifactFormula_GetReagent3QuantityForFormula", "Game", r"GAME::ItemArtifactFormula::GetReagent3QuantityForFormula\(void\)"),
    ("ItemArtifactFormula_GetReagent3Count", "Game", r"GAME::ItemArtifactFormula::GetReagent3Count\(class GAME::Character const"),
    ("ItemArtifactFormula_GetReagent4Id", "Game", r"GAME::ItemArtifactFormula::GetReagent4Id\(void\)"),
    ("ItemArtifactFormula_GetReagent4DisplayName", "Game", r"GAME::ItemArtifactFormula::GetReagent4DisplayName\(bool\)"),
    ("ItemArtifactFormula_GetReagent4QuantityForFormula", "Game", r"GAME::ItemArtifactFormula::GetReagent4QuantityForFormula\(void\)"),
    ("ItemArtifactFormula_GetReagent4Count", "Game", r"GAME::ItemArtifactFormula::GetReagent4Count\(class GAME::Character const"),
    ("ItemArtifactFormula_GetReagent5Id", "Game", r"GAME::ItemArtifactFormula::GetReagent5Id\(void\)"),
    ("ItemArtifactFormula_GetReagent5DisplayName", "Game", r"GAME::ItemArtifactFormula::GetReagent5DisplayName\(bool\)"),
    ("ItemArtifactFormula_GetReagent5QuantityForFormula", "Game", r"GAME::ItemArtifactFormula::GetReagent5QuantityForFormula\(void\)"),
    ("ItemArtifactFormula_GetReagent5Count", "Game", r"GAME::ItemArtifactFormula::GetReagent5Count\(class GAME::Character const"),
    ("ItemArtifactFormula_GetReagent6Id", "Game", r"GAME::ItemArtifactFormula::GetReagent6Id\(void\)"),
    ("ItemArtifactFormula_GetReagent6DisplayName", "Game", r"GAME::ItemArtifactFormula::GetReagent6DisplayName\(bool\)"),
    ("ItemArtifactFormula_GetReagent6QuantityForFormula", "Game", r"GAME::ItemArtifactFormula::GetReagent6QuantityForFormula\(void\)"),
    ("ItemArtifactFormula_GetReagent6Count", "Game", r"GAME::ItemArtifactFormula::GetReagent6Count\(class GAME::Character const"),
    ("Character_GetCurrentLifeInt", "Game", r"GAME::Character::GetCurrentLifeInt\(void\)"),
    ("GameEngine_SetSaveEnabled", "Game", r"GAME::GameEngine::SetSaveEnabled\(bool\)"),
    ("GameEngine_AutoSave", "Game", r"GAME::GameEngine::AutoSave\(void\)"),
    # equip / unequip / pickup (the exe's own sequences, 2026-08-22 readout)
    ("EquipmentCtrl_SmartAutoInsert", "Game", r"GAME::EquipmentCtrl::SmartAutoInsert\("),
    ("EquipmentCtrl_CanItemBePlaced", "Game", r"GAME::EquipmentCtrl::CanItemBePlaced\(enum"),
    ("InvCtrl_AddItem", "Game", r"GAME::PlayerInventoryCtrl::AddItem\(unsigned int,bool,bool\)"),
    ("InvCtrl_IsSpaceAvailable", "Game", r"GAME::PlayerInventoryCtrl::IsSpaceAvailable\(class GAME::Item const \* __ptr64\)const"),
    ("InvCtrl_IsSpaceAvailable2", "Game", r"GAME::PlayerInventoryCtrl::IsSpaceAvailable\(class GAME::Item const \* __ptr64,class GAME::Item const \* __ptr64\)const"),   # room for both hands of a two-hander swap
    ("ControllerCharacter_PickupItem", "Game", r"GAME::ControllerCharacter::PickupItem\("),
    ("ControllerPlayer_ItemAction", "Game", r"GAME::ControllerPlayer::ItemAction\("),
    ("ControllerPlayer_InteractAction", "Game", r"GAME::ControllerPlayer::InteractAction\("),
    ("Player_GetAlternateConfig", "Game", r"GAME::Player::GetAlternateConfig\(void\)"),
    ("HotSlotCtrl_SetPrimarySlot", "Game", r"GAME::PlayerHotSlotCtrl::SetPrimarySlot\(class GAME::HotSlotOption const"),
    ("HotSlotCtrl_SetSecondarySlot", "Game", r"GAME::PlayerHotSlotCtrl::SetSecondarySlot\(class GAME::HotSlotOption const"),
    # merchants / the caravan (the exe's sell and shift-click paths, 2026-08-22 readout)
    ("GameEngine_PlayerSaleRequest", "Game", r"GAME::GameEngine::PlayerSaleRequest\("),
    ("ControllerCharacter_SendRemoveItemFromInventory", "Game", r"GAME::ControllerCharacter::SendRemoveItemFromInventory\("),
    ("ControllerCharacter_SendAddItemToInventory", "Game", r"GAME::ControllerCharacter::SendAddItemToInventory\("),
    ("Player_AddItemToPrivateStash", "Game", r"GAME::Player::AddItemToPrivateStash\(unsigned int,unsigned int,bool\)"),
    ("Player_RemoveItemFromPrivateStash", "Game", r"GAME::Player::RemoveItemFromPrivateStash\("),
    ("Player_GetSelectedStashSackNumber", "Game", r"GAME::Player::GetSelectedStashSackNumber\("),
    ("GameEngine_AddItemToTransfer", "Game", r"GAME::GameEngine::AddItemToTransfer\(unsigned int,unsigned int,bool\)"),
    ("GameEngine_RemoveItemFromTransfer", "Game", r"GAME::GameEngine::RemoveItemFromTransfer\(unsigned int\)"),
    ("GameEngine_GetSelectedTransferSackNumber", "Game", r"GAME::GameEngine::GetSelectedTransferSackNumber\("),
    ("GameEngine_IsTransferOpen", "Game", r"GAME::GameEngine::IsTransferOpen\("),
    # Lua (dev probe): the engine's LuaManager sits at gEngine+0x68 (GameEngine::PostLuaInitialize)
    ("gEngine", "Engine", r"^class GAME::Engine \* __ptr64 __ptr64 GAME::gEngine$"),
    # Painted damage sectors (docs/hazards.md): the tick's own lookup chain, Level -> layers -> UniqueId -> SectorData
    ("Level_GetSectorLayers", "Engine", r"GAME::Level::GetSectorLayers\(void\)"),
    ("SectorLayers_GetTargetId", "Engine", r"GAME::SectorLayers::GetTargetId\(int,int,int\)"),
    ("SectorDataManager_GetSectorData", "Engine", r"GAME::SectorDataManager::GetSectorData\(unsigned int,class GAME::UniqueId const"),
    ("LuaManager_RunCode", "Engine", r"GAME::LuaManager::RunCode\(char const"),
    ("LuaManager_Load", "Engine", r"GAME::LuaManager::Load\("),
    # Pets (docs/re_pets_gamedll.md, 2026-08-26): the local pet list, the pen (pet -> summoning skill), stance
    # (per SKILL: Player's map keyed by skill id + Monster::UseController on the pet), commands, disband.
    ("GameEngine_GetLocalPetList", "Game", r"GAME::GameEngine::GetLocalPetList\(void\)"),
    ("GameEngine_RegisterLocalPet", "Game", r"GAME::GameEngine::RegisterLocalPet\("),
    ("GameEngine_UnregisterLocalPet", "Game", r"GAME::GameEngine::UnregisterLocalPet\("),
    ("Character_GetPetPen", "Game", r"^public: class GAME::PetPen & __ptr64 __cdecl GAME::Character::GetPetPen\(void\)"),
    ("PetPen_GetPetOwner", "Game", r"GAME::PetPen::GetPetOwner\("),
    ("Player_GetPetControllerType", "Game", r"GAME::Player::GetPetControllerType\("),
    ("Player_SetPetControllerType", "Game", r"GAME::Player::SetPetControllerType\("),
    ("Monster_UseController", "Game", r"GAME::Monster::UseController\(enum"),
    ("Character_RequestAttack", "Game", r"^public: void __cdecl GAME::Character::RequestAttack\(unsigned int,unsigned int\)"),
    ("Character_RequestMove", "Game", r"^public: void __cdecl GAME::Character::RequestMove\(unsigned int,class GAME::WorldVec3 const"),
    ("ControllerPlayer_ReleasePet", "Game", r"GAME::ControllerPlayer::ReleasePet\("),

]
tables = {}
for dll in ("Engine", "Game", "DirectInput"):
    rows = []
    with open(os.path.join(HERE, "exports", f"{dll}.x64.txt"), encoding="utf-8") as f:
        for line in f:
            und, _, dec = line.rstrip("\n").partition("\t")
            rows.append((und, dec))
    tables[dll] = rows
out = ["// GENERATED by tools/gen_names.py -- do not edit", "#pragma once", "namespace gd::names {"]
ok = True
for ident, dll, rx in ENTRIES:
    m = [(u, d) for u, d in tables[dll] if re.search(rx, u)]
    if len(m) != 1:
        ok = False
        print(f"!! {ident}: {len(m)} matches", file=sys.stderr)
        for u, d in m[:6]: print("     ", u[:200], file=sys.stderr)
        continue
    out.append(f'// {m[0][0][:220]}')
    out.append(f'inline constexpr const char* {ident}_DLL = "{dll}.dll";')
    out.append(f'inline constexpr const char* {ident} = "{m[0][1]}";')
out.append("}  // namespace gd::names")
if not ok: sys.exit(1)
with open(os.path.join(HERE, "..", "src", "gd_names.h"), "w", encoding="utf-8", newline="\n") as f: f.write("\n".join(out) + "\n")
print(f"wrote src/gd_names.h with {len(ENTRIES)} names")
